inventory_app/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', function () {
	    return redirect('dashboard');
	}); 
	Route::get('home', function () {
	    return redirect('dashboard');
	}); 

	Route::controller('dashboard', 'DashboardController');
	Route::controller('history', 'HistoryController');

	Route::resource('invoice', 'InvoiceController');
	Route::resource('delivered', 'DeliveredController');
	Route::resource('detail', 'DetailController');
	Route::resource('quantity', 'QuantityController');
	Route::resource('export', 'ExportController');

	Route::resource('settings/size_matrix', 'SizeMatrixController');
	Route::resource('settings/price_rule', 'PriceRuleController');
	Route::controller('settings/{option}', 'OptionsController' );

	Route::resource('user', 'UserController' );

	// Registration routes...
	Route::get('auth/register', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');	

	// Password reset routes...
	Route::get('password/reset/{user}', 'Auth\PasswordController@getReset');
	Route::post('password/reset', 'Auth\PasswordController@postReset');
});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

inventory_app/app/Detail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Detail extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'detail';

    /**
     * Get the Category that owns the Invetory_Prep item.
     */
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    /**
     * Get the Category that owns the Invetory_Prep item.
     */
    public function online_color()
    {
        return $this->belongsTo('App\Online_Color');
    }
}

inventory_app/app/Http/Controllers/DetailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class DetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // Query all open Invoices
        $invoices = App\Invoice::open()->get();

        return view('detail.index', ['invoices' => $invoices, 'page' => 'detail.index']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  Request  $request
     * @return Response
     */
    public function create(Request $request)
    {
        $invoice = App\Invoice::findorFail($request->id);
        $colors = App\Online_Color::all();
        $cat = App\Category::all();

        return view('detail.create', [ 
            'invoice' => $invoice, 
            'colors' => $colors, 
            'categories' => $cat,
            'page' => 'detail.create'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        // Store request
        $details = $request->all();

        // validate items in table
        for ($i=0; $i < count($details); $i++) { 
            $this->validate($request, [
                $i.'.id' => 'required|unique:detail,inventory_prep_id',
                $i.'.brand' => 'required|max:31',
                $i.'.category' => 'required|exists:category,name',
                $i.'.online_color' => 'required|exists:online_color,name',
            ]);
        };

        // loop through table to save items
        foreach ($details as $item) {
            $category = App\Category::where('name', $item['category'])->firstOrFail()->id;
            $color = App\Online_Color::where('name', $item['online_color'])->firstOrFail()->id;

            $detail = new App\Detail;

            $detail->brand             = $item['brand'];
            $detail->category_id       = $category;
            $detail->online_color_id   = $color;
            $detail->inventory_prep_id = $item['id'];

            $detail->save();

            // change detail_set flag to true
            $inventory_prep = App\Inventory_Prep::findOrFail($item['id']);

            $inventory_prep->detail_set = true;

            $inventory_prep->save();
        }
        return json_encode(array('status' => 'success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

inventory_app/resources/views/detail/create.blade.php
{{-- List styles to import --}}

@extends('master')

@section('head')
	{{-- This is required by any page that will use the Handsontable --}}
	@include('include.table_heads')
@endsection


@section('title', 'Details')


@section('content')
</br>
</br>
</br>
</br>
Invoice: {{$invoice->id}} <br>

<button name="save" id="save" data="#detail" data-instance="hotInstance">Save</button>
  

<p id="msg"></p>

Enter details of invenotry items: 

<meta name="csrf_token" content="{{ csrf_token() }}" />

<!-- Table -->
<div id="detail"></div>
@endsection

@section('js')
  <script src="http://handsontable.com/dist/handsontable.full.js"></script>

<script>

	// load style data
	var preLoadData = [
  @foreach($invoice->inventory_prep as $item)
  {
      id: '{{$item->id}}',
      style: '{{$item->style}}', 
      size: '{{$item->size_matrix->name}}', 
      department: '{{$item->department->name}}', 
      color: '{{$item->color}}'
    },
  @endforeach
    ];


  // Instead of creating a new Handsontable instance
  // with the container element passed as an argument,
  // you can simply call .handsontable method on a jQuery DOM object.
  var $container = $("#detail");

  $container.handsontable({
    data: preLoadData,    // must be define for dataSchema to work and return data as Objects
    dataSchema: {
    	style: null, 
    	size: null, 
    	department: null, 
    	color: null, 
      online_color: null,
      category: null,
      brand: null
    }, 

    rowHeaders: true,
    colHeaders: true,
    contextMenu: true,
    undo: true,

    startRows: 1,
    minSpareRows: 0,
    maxRows: preLoadData.numberOfRows,
    
    manualColumnResize: true,
    manualRowResize: true,
    colWidths: [120, 70, 120, 120, 120, 120, 120],
    colHeaders: ['Style', 'Size', 'Department', 'Color', 'Online Color', 'Category', 'Brand'],

    columns: [
      {
        data: 'style', 
        readOnly: true
      },
      {
        data: 'size', 
        readOnly: true
      },
      {
        data: 'department', 
        readOnly: true
      },
      {
        data: 'color', 
        readOnly: true
      },
      {
      	data: 'online_color',
        type: 'dropdown',
      	source: [    
          @foreach($colors as $color)
            '{{$color->name}}',
          @endforeach
        ] 
      },
      {
      	data: 'category',
        type: 'dropdown',
      	source: [    
          @foreach($categories as $category)
            '{{$category->name}}',
          @endforeach
        ] 
      },
      {
      	data: 'brand',
      }
    ],
    cells: function () {
          
    },
    // Validation on check will occur on the entire table and will aler if fail
    afterDeselect: function (callback) {

    },
    afterChange: function (change, source) {

    },
    // change [[row, prop, oldVal, newVal], ...]
    // string "alter", "empty", "edit", "populateFromArray", "loadData", "autofill", "paste"  
    beforeChange: function (change, source) {
      // this will limit size of ALL cells
      var sizelimit = 120;

      //** Need to limit size of line that can be paste in

      // Makes sure that the string is below size limit designated
      for (var i = 0; i < change.length; i++) {
        var newVal = change[i][3];

        if ( newVal.length >= sizelimit ) {
          change[i][3] = newVal.substr(0, sizelimit);
          //** Alert user that size limit has bee exceeded
        }


      };

    }
  });

  // buttons check for array(null)


  /**
   * A usually small function or regular expression that validates the input.
   * After you determine if the input is valid, execute `callback(true)` or `callback(false)` to proceed with the execution.
   * In function, `this` binds to cellProperties.
   *
   * @type {Function|RegExp}
   * @default undefined
   * @since 0.9.5
   */
  // validator: void 0,





  // This way, you can access Handsontable api methods by passing their names as an argument, e.g.:
  var hotInstance = $("#detail").handsontable('getInstance');


  (function () {
    function bindButtons() {
      if (typeof Handsontable === "undefined") {
        return;
      }

      Handsontable.Dom.addEvent(document.body, 'click', function(e) {

        // get instace for button clicked
        var element = e.target || e.srcElement;
        var name = element.getAttribute('data');
        var instance = element.getAttribute('data-instance');
        var hot = window[instance];        

        if (element.nodeName == "BUTTON") {
          // Check wich button was pressed
          switch (element.name) {

            case 'dump':
              dump(hot)
              break;

            case 'save':
              console.log('save button');
              save(hot);

              break;
          }

        }
      });
    }
    bindButtons();

    function dump(element) {
      console.log(document.getElementById('port_id').value)
      //console.log('function dump:' + JSON.stringify(element.getData()))
    }

    function save(hot) {

      $.ajax({
        url: "{{ route('detail.store') }}", 
        method: 'POST',
        data: JSON.stringify(hot.getSourceData()),//{ form : formdata, table : JSON.stringify(hot.getData()}), // returns all cell data
        contentType: "application/json; charset=utf-8",
        dataType: 'json',

        beforeSend: function (xhr) {
          // checks for an empty table
          if (hot.countRows() == hot.countEmptyRows()) { 
            alert('Failed to save. Table has no data.'); 
            return false;
          };

          //checks for empty columns
          // if (hot.countEmptyCols() > 0) {
          //   alert('Failed to save. Table has empty columns.'); 
          //   return false;          
          // };

          // check for empty rows not at the end of the table, those will be trimed later
          if ((hot.countEmptyRows() - hot.countEmptyRows(true)) > 0) {
            alert('Failed to save. Table has empty rows.'); 
            return false;          
          };


          // needed to get pass auth middleware   
          var token = $('meta[name="csrf_token"]').attr('content');

          if (token) {
            return xhr.setRequestHeader('X-CSRF-TOKEN', token);
          }
        },

        success:function(data){
          // check response
          if (data.status == 'success') {
          	alert('Invoice was successfully saved.');
         	  hot.updateSettings({
                cells: function (row, col, prop) {
                  var cellProperties = {};

                    cellProperties.readOnly = true;

                  return cellProperties;
                }
              });
            //window.location.replace('{{ url('invoice') }}'+'/'+data.invoice_id );
          }else{
          	alert('There was an eror, please contact Developoment');
          };

        },

        error:function(data){
          // ** turn this into alert
          alert('There was an error with the submit, please check your data and try again. If problem persist contact Developoment team.');
        }
      })
    } 
  })();        
</script>
@endsection

inventory_app/resources/views/detail/index.blade.php
@extends('master')

@section('head')
    <style>
    /*table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: left;
    }*/
    </style>
@endsection


@section('title', 'Detail')


@section('content')
    <div><h1>All Submited Forms</h1></div>

    </br></br>
    <table style="width:100%">
    	<tr>
    		<th>Invoice ID</th>
    		<th>Vendor</th>
    		<th>Notes</th>
            <th>Page</th>
    		<th># of Items</th>
            <th>Created by</th>
    		<th>Created date</th>
    	</tr>
        @foreach($invoices as $invoice)
          <tr>
            <td><a href="{{ route('invoice.show', ['id' => $invoice->id]) }}">
            {{$invoice->invoice_number}} 
            </a></td>
            <td>{{$invoice->vendor->name}}</td>
            <td>{{$invoice->notes}}</td>
            <td>{{$invoice->page_number}} of {{$invoice->total_pages}}</td>
            <td>{{count($invoice->inventory_prep)}}</td>
            <td>{{$invoice->created_by}}</td>
            <td>{{$invoice->created_at}}</td>
          </tr>
        @endforeach
    </table>


    </br>
    <br>
    <br>
    <a href="{{ url('dashboard') }}">Go back to dashboard</a>
@endsection